Default: &defaults
  database: Simple.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Simple_test.sqlite3
  <<: *defaults

Staging:
  database: Simple_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Simple_production.sqlite3
  poolsize: 100
  <<: *defaults
